### ISSUE TITLE
Callisto Hardfork Meta

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/go-callisto#20]
- [x] ~~Merge Upstream v1.8.14 release to master [WIP]~~ Changed to Multi-Geth upstream
- [x] ~~Merge master to CLO/1.0 branch~~ Also changed to Multi-Geth upstream
- [x] Refactor CLO reward consensus
- [ ] Move cold staking address to deployed smart contract ( Will be moved after deployment )
- [ ] POW Testnet for CLO hardfork
- [ ] Documentation for Users & Pool operators
- [ ] Announce hardfork & upgrade guide

**Comment by yograterol** [comment]
@akx20000a we should manage the HF1 as CLO/1.1 to keep the branch CLO/1.0 without changes.
